/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'Unicorns R Us Is Bullshit',
  tagline: 'Debunking the nonsense, one claim at a time',
  favicon: 'img/favicon.ico',

  future: {
    v4: true,
  },

  url: 'https://unicorns-r-us-is-bullshit.com',
  baseUrl: '/',

  onBrokenLinks: 'throw',

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  clientModules: ['./src/progress-bar.js'],

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: false,
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      }),
    ],
  ],

  headTags: [
    // Open Graph defaults (page-level description overrides via frontmatter)
    {tagName: 'meta', attributes: {property: 'og:type', content: 'website'}},
    {tagName: 'meta', attributes: {property: 'og:site_name', content: 'Unicorns R Us Is Bullshit'}},
    {tagName: 'meta', attributes: {property: 'og:image', content: 'https://unicorns-r-us-is-bullshit.com/img/og-image.jpg'}},
    {tagName: 'meta', attributes: {name: 'twitter:card', content: 'summary_large_image'}},
    // Favicon tags (generated by realfavicongenerator.net)
    {tagName: 'link', attributes: {rel: 'icon', type: 'image/png', href: '/img/favicon-96x96.png', sizes: '96x96'}},
    {tagName: 'link', attributes: {rel: 'icon', type: 'image/svg+xml', href: '/img/favicon.svg'}},
    {tagName: 'link', attributes: {rel: 'shortcut icon', href: '/img/favicon.ico'}},
    {tagName: 'link', attributes: {rel: 'apple-touch-icon', sizes: '180x180', href: '/img/apple-touch-icon.png'}},
    {tagName: 'link', attributes: {rel: 'manifest', href: '/img/site.webmanifest'}},
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      metadata: [
        {name: 'description', content: 'An evidence-based rebuttal of the Unicorns-R-Us website and how it gets weaponized in polyamorous communities.'},
        {name: 'keywords', content: 'unicorn hunting, polyamory, unicorns-r-us, ethical non-monogamy, triad, couple privilege, poly community'},
      ],
      colorMode: {
        defaultMode: 'light',
        respectPrefersColorScheme: true,
      },
      navbar: {
        title: 'Unicorns R Us Is Bullshit',
        items: [
          {
            to: '/',
            label: '🦄 Home',
            position: 'left',
            activeBaseRegex: '^/$',
          },
          {
            to: '/poly-police',
            label: '🚨 Poly Police',
            position: 'left',
          },
        ],
      },
      footer: {
        style: 'dark',
        links: [],
        copyright: `Content licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="noopener noreferrer">CC BY-NC-SA 4.0</a>.`,
      },
    }),
};

export default config;
